### ISSUE TITLE
What still needs to be done?

### ISSUE THREAD

**Issue by bilbobaggins30** [MatejTymes/JavaFixes#1]
What is your direction with this project? I would like to lend a hand, wherever needed!

**Comment by MatejTymes** [comment]
Hi. I was quite positively surprised that somebody wanted to help, and thank you. Unfortunately because I was working alone so far I haven't defined separate pieces of work yet.

Currently I want to concentrate on ZeroD now as what I wanted for initial implementation of JavaFixes is finished so far (i'll be putting it into a maven repository soon).

The Decimal code though is still in progress and is planned to go into second release (1.1.0) as it requires quite a big chunk of work. Not sure if you would like to take a look at it. I'll try to think of some more specific tasks in the meantime.

**Comment by bilbobaggins30** [comment]
What IDE are you using BTW? I was using NetBeans, but trying to open this project looks to be... Fun....

**Comment by bilbobaggins30** [comment]
I did see some ToDo comments, and can jump on those, and do Pull Requests. I have been looking for a fun weekend project like this for some time ;-)
